name: Push

on:
  push:
    branches:
      - main

jobs:

  install:
    uses: bagonboard/github-actions/.github/workflows/install.yml@master

  tests:
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        script:
          [
            "test:e2e:ci",
          ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - run: npm run ${{ matrix.script}}
        env:
          REACT_APP_HOST_ENV: local

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: playwright-test-results
          path: "test-results/**/*"

