name: Push

on:
  push:
    branches:
      - main

jobs:

  install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:     
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

  tests:
    needs: [install]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        script:
          [
            "test:e2e:ci",
          ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - run: npm run ${{ matrix.script}}
        env:
          REACT_APP_HOST_ENV: local

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: playwright-test-results
          path: "test-results/**/*"
